version: '3'
services:
  db: 
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - postgres:/var/lib/postgresql/data
  web: 
    build: .
    volumes: 
      - .:/myapp
    ports:
    - "3000:3000"
    # Ports required for debugging
    - "1234:1234"
    - "26166:26168"
    depends_on: 
      - db
volumes:
  postgres:
  bundler_gems: 