default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 
  host: <%= ENV['DEVELOPMENT_DATABASE_HOST'] %>

development:
  <<: *default
  database: dojo_api_development

test:
  <<: *default
  database: dojo_api_test

production:
  <<: *default
  database: dojo_api_production
  username: dojo_api
  password: <%= ENV['DOJO_API_DATABASE_PASSWORD'] %>
